sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # Download and Install google cloud sdk.
  - source $HOME/google-cloud-sdk/path.bash.inc
  # Apply some configurations to the current shell using the source command.
  - gcloud components update kubectl
  # Install and update kubectl as part of the Google Cloud SDK in the Travis environment
  - gcloud auth activate-service-account --key-file service-account.json
  # Activate the Google Cloud service account by providing a set of credentials.