apiVersion: v1
kind: PersistentVolumeClaim
# An claim of storage options that would be allocated by Kubernetes, either with storage instance already prepared 
# (Statically provisioned persistent volume), or have to be created on the go (Dynamically provisioned persistent volume).
metadata: 
  name: database-persistent-volume-claim
spec:
  accessModes:
  # 3 different types of accessModes: 
  # ReadWriteOnce: Can be used by a single node 
  # ReadOnlyMany: Multiple nodes can read from this
  # ReadWriteMany: Can be read and written to by many nodes
    - ReadWriteOnce
  resources: 
    requests:
      storage: 2Gi